version: '3'

services:
    user-service:
      build:
        context: ./../


    
    redis:
     image: 'redis:alpine'
     ports:
      - "6379:6379"
     restart: always
     volumes:
      - ./db-data/redis/:/data